<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Putaway Sheet</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        .barcode {
            display: block;
            margin: 0 auto;
            max-width: 250px;
        }

        .table th,
        .table td {
            padding: 0;
            text-align: center;
            vertical-align: middle;
        }

        .print-button {
            margin: 20px;
            text-align: center;
        }
    </style>
</head>

<body onload="print()">

    <div class="container mt-5">
        <h2 class="text-center">Putaway Sheet</h2>
        <div class="row mb-4 mt-4">
            <div class="col text-center">
                <strong>Putaway Number:</strong> <?= $rcv->putaway_number ?><br>
                <svg class="barcode" jsbarcode-format="CODE128" jsbarcode-value="<?= $rcv->putaway_number ?>" jsbarcode-textmargin="0" jsbarcode-fontoptions="bold"></svg>
            </div>
            <div class="col text-center">
                <strong>Receive Number:</strong> <?= $rcv->receive_number ?><br>
                <svg class="barcode" jsbarcode-format="CODE128" jsbarcode-value="<?= $rcv->receive_number ?>" jsbarcode-textmargin="0" jsbarcode-fontoptions="bold"></svg>
            </div>
        </div>
        <table class="table table-bordered mt-4">
            <thead>
                <tr>
                    <th>No.</th>
                    <th>Item Code</th>
                    <th>LPN Number</th>
                    <th class="text-center p-2">Qty</th>
                </tr>
            </thead>
            <tbody id="putaway-table">
                <!-- Rows will be generated by JavaScript -->
                <?php $no = 1;
                foreach ($rcv_detail as $row) { ?>
                    <tr>
                        <td><?= $no++ ?></td>
                        <td>
                            <svg class="barcode" jsbarcode-format="CODE128" jsbarcode-value="<?= $row->item_code ?>" jsbarcode-textmargin="0" jsbarcode-fontoptions=""></svg>
                        </td>
                        <td>
                            <svg class="barcode" jsbarcode-format="CODE128" jsbarcode-value="<?= $row->lpn_number ?>" jsbarcode-textmargin="0" jsbarcode-fontoptions=""></svg>
                        </td>
                        <td><?= $row->qty ?></td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
        <!-- <div class="print-button text-center">
            <button class="btn btn-primary" onclick="window.print()">Print</button>
        </div> -->
    </div>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <!-- JsBarcode Library for barcode generation -->
    <script src="https://cdn.jsdelivr.net/npm/jsbarcode@3.11.5/dist/JsBarcode.all.min.js"></script>
    <script>
        $(document).ready(function() {

            // Sample data for demonstration
            const data = [{
                    no: 1,
                    location: 'RACK-A01',
                    itemCode: 'ITEM-12345',
                    lpnNumber: 'LPN00001',
                    quantity: 10
                },
                {
                    no: 2,
                    location: 'RACK-B02',
                    itemCode: 'ITEM-67890',
                    lpnNumber: 'LPN00002',
                    quantity: 20
                },
                {
                    no: 3,
                    location: 'RACK-C03',
                    itemCode: 'ITEM-54321',
                    lpnNumber: 'LPN00003',
                    quantity: 15
                },
                {
                    no: 4,
                    location: 'RACK-D04',
                    itemCode: 'ITEM-09876',
                    lpnNumber: 'LPN00004',
                    quantity: 25
                },
                {
                    no: 5,
                    location: 'RACK-E05',
                    itemCode: 'ITEM-13579',
                    lpnNumber: 'LPN00005',
                    quantity: 30
                }
            ];

            // Function to generate the table rows
            function generateTable() {
                // const tableBody = document.getElementById("putaway-table");
                // data.forEach(item => {
                //     const row = document.createElement("tr");

                //     row.innerHTML = `
                //     <td>${item.no}</td>
                //     <td>${item.location}</td>
                //     <td>
                //         <svg class="barcode" jsbarcode-format="CODE128" jsbarcode-value="${item.itemCode}" jsbarcode-textmargin="0" jsbarcode-fontoptions=""></svg>
                //     </td>
                //     <td>
                //         <svg class="barcode" jsbarcode-format="CODE128" jsbarcode-value="${item.lpnNumber}" jsbarcode-textmargin="0" jsbarcode-fontoptions=""></svg>
                //     </td>
                //     <td>${item.quantity}</td>
                // `;

                //     tableBody.appendChild(row);
                // });

                // Generate barcodes after rows are added to the table
                JsBarcode(".barcode").init();
            }
            generateTable()

            // Initialize the table on page load
            // document.addEventListener("DOMContentLoaded", generateTable);

            window.addEventListener("afterprint", () => {
                window.close();
            });

        });
    </script>
</body>

</html>